### ISSUE TITLE
Light curve not displayed on the scanning page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#134]
Hi,

I am scanning today. Some objects do not have a light curve (see attached plot).

Cheers,

Steve
![Screenshot from 2020-12-10 09-50-51](https://user-images.githubusercontent.com/11585543/101748797-4bd6b100-3acd-11eb-83e3-d9e548338641.png)

**Comment by dannygoldstein** [comment]
@dmitryduev I think the plots end up looking like this when there is no photometry viewable by the user. But how can that be possible, if the objects are on the scanning page?

**Comment by dmitryduev** [comment]
Yea, this shouldn't be possible. I've seen such behavior when the app is under significant load and the corresponding API calls time out, so nothing gets displayed on the scanning page. @steveschulze what happens when you click on one of those candidates? Can you see the photometry on the Source page?
