### ISSUE TITLE
Slider (left right) on user management

### ISSUE THREAD

**Issue by ivonata** [fritz-marshal/fritz#187]
Please fill out relevant sections below; remove those that are unused.

**Feature Summary**
Is it possible to have the slider (left right) one appear all the time on the User Management page. The scenario is as follows. I need to find a user (I only know their name , not username). To do that now, I have to first choose to display 200 entries for the table of users (basically all users). They I look for the name with CTRL+F and I find it. Now, I need to edit the Streams for this person but Streams is the last column in the table and I can't see it. There is no slider I can use to navigate to the last column for the selected person. To access the slider, I need to go all the way to the bottom of the page. However, now, if I slide to the end of the table to see "Streams", I can't see the names so I can't get back to the name of the user I am looking for (I can only see the  email column partially).  

**Usage / behavior**
just a basic slider that is available all the time for the user table will solve the problem.

**Alternative Solutions**
Are there any alternatives to the proposed feature that we should consider implementing?

**Implementation details**
If you have any insight on how this feature can be implemented, please provide that information here.

**Additional context**

**Comment by kmshin1397** [comment]
Hi @ivonata,

One method that could help with this issue that you may not have discovered yet is the "View Columns" tool on the table. It's the three vertical bars icon at the top right of the table. You can choose to turn off certain columns that you don't need to see so that the Streams column doesn't extend off the page. That way you wouldn't need the slider at all. You could have just a two-column table with the name and the streams, for example, if that's all you need.

![image](https://user-images.githubusercontent.com/17696889/110142966-b6ce1600-7da4-11eb-8389-db535411e22e.png)

We can certainly look into a pinned slider like you suggest if my suggestion doesn't fit your needs :)

**Comment by kmshin1397** [comment]
Closing since the show columns functionality addresses the concern
